--Every command here will be executed when the container is created

CREATE TABLE CATEGORIES (
    CODE SERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    TAX NUMERIC(10,2)
);

CREATE TABLE PRODUCTS (
    CODE_PROD SERIAL PRIMARY KEY,
    NAME_PROD VARCHAR(255),
    PRICE NUMERIC(10,2),
    AMOUNT INTEGER,
    CATEGORY_CODE INTEGER,
    CONSTRAINT FK_CATEGORY FOREIGN KEY (CATEGORY_CODE) REFERENCES CATEGORIES(CODE)
);

CREATE TABLE ORDERS (
    CODE_ORDERS SERIAL PRIMARY KEY,
    TOTAL NUMERIC(10,2),
    TAX NUMERIC(10,2)
);

CREATE TABLE ORDER_ITEM(
    CODE_ORDER_ITEM SERIAL PRIMARY KEY,
    ORDER_CODE INTEGER,
    PRODUCT_CODE INTEGER,
    AMOUNT INTEGER,
    PRICE NUMERIC(10,2),
    TAX NUMERIC(10,2),
    CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_CODE) REFERENCES PRODUCTS(CODE_PROD),
    CONSTRAINT FK_ORDER FOREIGN KEY (ORDER_CODE) REFERENCES ORDERS(CODE_ORDERS)
);

CREATE TABLE CART(
    ID SERIAL PRIMARY KEY,
    PRODUCT_TEMP_CODE INTEGER,
    AMOUNT_TEMP INTEGER,
    PRICE NUMERIC(10,2),
    TAX NUMERIC(10,2),
    TOTAL NUMERIC(10,2),
    TOTAL_TAXA NUMERIC(10,2),
    CONSTRAINT FK_PRODUCT_CART FOREIGN KEY (PRODUCT_TEMP_CODE) REFERENCES PRODUCTS(CODE_PROD)
);